{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-mcp-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-mcp-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}

