{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  argocd-token: {{ .Values.secrets.argocdToken | b64enc | quote }}
  gitlab-token: {{ .Values.secrets.gitlabToken | b64enc | quote }}
  claude-api-key: {{ .Values.secrets.claudeApiKey | b64enc | quote }}
{{- end }}

